"use client";

import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Card,
  CardDescription,
  CardHeader,
  CardSection,
  CardTitle,
} from "@/components/ui/card";

type State = { success: boolean; message: string };
const INITIAL: State = { success: false, message: "" };

interface Props {
  campaignId: string;
  existing: {
    summary: string;
    observations: string;
    recommendations: string;
  } | null;
  action: (prevState: State, formData: FormData) => Promise<State>;
}

export function ModeratorReportForm({ campaignId, existing, action }: Props) {
  const [state, formAction, pending] = useActionState(action, INITIAL);

  return (
    <Card padding="none">
      <CardHeader>
        <CardTitle>{existing ? "Update your report" : "Submit your report"}</CardTitle>
        <CardDescription>
          Your summary, observations, and recommendations will appear as a dedicated section in the
          final PDF generated by the test manager.
        </CardDescription>
      </CardHeader>
      <CardSection className="border-t border-slate-100/90">
        <form action={formAction} className="space-y-5">
          <input type="hidden" name="campaignId" value={campaignId} />

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700" htmlFor="summary">
              Summary <span className="text-red-500">*</span>
            </label>
            <p className="text-xs text-slate-500">
              A concise overview of the moderation work done — quality of submissions, overall
              tester engagement, and any blocking issues encountered.
            </p>
            <Textarea
              id="summary"
              name="summary"
              required
              defaultValue={existing?.summary ?? ""}
              placeholder="Overall the campaign produced X bug reports across Y testers. The quality was…"
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700" htmlFor="observations">
              Key Observations
            </label>
            <p className="text-xs text-slate-500">
              Patterns you noticed: recurring bug types, problematic environments, tester reliability,
              or unusual behaviours worth highlighting to the test manager.
            </p>
            <Textarea
              id="observations"
              name="observations"
              defaultValue={existing?.observations ?? ""}
              placeholder="Most issues were concentrated on Android / Chrome. Several testers submitted…"
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700" htmlFor="recommendations">
              Recommendations
            </label>
            <p className="text-xs text-slate-500">
              Actionable suggestions for the development team or future campaigns based on what you
              observed.
            </p>
            <Textarea
              id="recommendations"
              name="recommendations"
              defaultValue={existing?.recommendations ?? ""}
              placeholder="We recommend focusing regression testing on… A follow-up session targeting…"
            />
          </div>

          {state.message && !state.success ? (
            <p className="text-sm text-red-600">{state.message}</p>
          ) : null}

          <Button type="submit" disabled={pending}>
            {pending ? "Submitting…" : existing ? "Update report" : "Submit report"}
          </Button>
        </form>
      </CardSection>
    </Card>
  );
}
